flags: {}
packages:
- 'eclogues'
- 'eclogues-mock'
- 'eclogues-impl'
- location:
    git: https://github.com/chrisdone/path
    commit: 9af2a76b2e587c6f763c7e6eae53285f49e1c95d
  extra-dep: true
- location:
    git: https://github.com/rimmington/units
    commit: 7e11e858387923ad793115e6f2bdca5af968ccf4
  extra-dep: true
- location:
    git: git@github.com:rimmington/thrift-hs
    commit: 6fe95c60d5085723fc49ed8e156cae8dd151456f
  extra-dep: true
- location:
    git: git@github.com:rimmington/path-io
    commit: b5e6eeab41b77b435650425e7f8c1720ff27eaeb
  extra-dep: true
- location:
    git: git@github.com:ssilab/digital-metrology-frontiers
    commit: 87053f6e5892df1f1d7dc3bf85ee2677e7a41bf8
  extra-dep: true
- location:
    git: git@github.com:ssilab/aegle
    commit: 176070ee5bb72f8ab2d3c9301d02bf5a1b0327c3
  subdirs:
  - 'aegle'
  extra-dep: true
- location:
    git: git@github.com:ssilab/hzk-elections
    commit: 7394c729bf8f8c517aa60c020a2b21f13a9265a8
  extra-dep: true
extra-deps:
- data-default-generics-0.3
- hzk-2.1.0
- stm-io-hooks-1.1.0
- uuid-aeson-0.1.0.0
- xdg-basedir-0.2.2
- units-attoparsec-1.0
- units-defs-2.0.0.1
- units-parser-0.1.0.0
- microlens-0.3.4.0
- protobuf-0.2.1.0
- pipes-cereal-0.1.0.0
resolver: lts-3.9
